# Generated by Django 3.2 on 2021-10-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, default='000', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
